#!/bin/bash




alias vim="nvim"
alias ll="ls -lah"
alias ls="ls -a"
alias ghel="cd /media/francesco/tartarughello/"
alias notes="nvim /home/francesco/Documents/Notes"
alias nx="nix-env"


#confim befor ocerwriting
alias cp="cp -i" 
alias mv="mv -i"
alias rm="rm -i"

alias df="df -h"

#colors if interctive
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

